name: wisy_camera
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.3
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.10
  flutter_riverpod: ^2.3.6
  camerawesome: ^1.4.0
  path_provider: ^2.0.14
  better_open_file: ^3.6.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
